led.enable(false)
pins.servoWritePin(AnalogPin.P6, 180)
pins.servoWritePin(AnalogPin.P7, 180)
pins.servoWritePin(AnalogPin.P8, 180)
pins.servoWritePin(AnalogPin.P9, 180)
basic.forever(function () {
    pins.servoWritePin(AnalogPin.P6, 180)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P7, 180)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P8, 180)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P9, 180)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P9, 0)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P8, 0)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P7, 0)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P6, 0)
    basic.pause(500)
})
